version: 2.0

jobs:
  test:
    parallelism: 2
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      - image: circleci/mysql:8.0.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: bgsm
          MYSQL_USER: robert
          MYSQL_PASSWORD: robertpassword
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - attach_workspace:
          at: ./target
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
            nc -z 127.0.0.1 3306 && echo Success && exit 0
            echo -n .
            sleep 1
            done
            echo Failed waiting for MySQL && exit 1
            - run:
                name: Install MySQL CLI; Import dummy data; run an example query
                command: |
                  sudo apt-get install default-mysql-client
                  mysql -h 127.0.0.1 -u robert -robertpassword bgsm < sql-data/dummy.sql
                  mysql -h 127.0.0.1 -u robert -robertpassword --execute="SELECT * FROM test_db.Persons"
      - run:
          name: Run tests eureka
          command: |
            cd eureka
            sudo chmod +x ./mvnw
            ./mvnw \
            -Dtest=$(for files in $(circleci tests glob "src/test/**/**.java" \
            | circleci tests split --split-by=timings); \
            do basename $file \
            | sed -e "s/.java/,/"; \
            done | tr -d '\r\n') \
            -e test verify
      - store_test_results:
          path: eureka/target/surefire-reports
      - store_artifacts:
          path: eureka/target/site/jacoco/index.html
      - run:
          name: Run tests user-service
          command: |
            cd user-service
            sudo chmod +x ./mvnw
            ./mvnw \
            -Dtest=$(for files in $(circleci tests glob "src/test/**/**.java" \
            | circleci tests split --split-by=timings); \
            do basename $file \
            | sed -e "s/.java/,/"; \
            done | tr -d '\r\n') \
            -e test verify
      - store_test_results:
          path: user-service/target/surefire-reports
      - store_artifacts:
          path: user-service/target/site/jacoco/index.html
      - run:
          name: Run tests gui-service
          command: |
            cd gui-service
            sudo chmod +x ./mvnw
            ./mvnw \
            -Dtest=$(for files in $(circleci tests glob "src/test/**/**.java" \
            | circleci tests split --split-by=timings); \
            do basename $file \
            | sed -e "s/.java/,/"; \
            done | tr -d '\r\n') \
            -e test verify
      - store_test_results:
          path: gui-service/target/surefire-reports
      - store_artifacts:
          path: gui-service/target/site/jacoco/index.html

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Maven package eureka
          command: |
            cd eureka
            sudo chmod +x ./mvnw
            ./mvnw -Dmaven.test.skip=true package
      - run:
          name: Maven package user-service
          command: |
            cd user-service
            sudo chmod +x ./mvnw
            ./mvnw -Dmaven.test.skip=true package
      - run:
          name: Maven package gui-service
          command: |
            cd gui-service
            sudo chmod +x ./mvnw
            ./mvnw -Dmaven.test.skip=true package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: ./
          paths:
            - eureka/target/
            - user-service/target/
            - gui-service/target/

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build